version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: data/logs/github_tracker.log
    encoding: utf8

loggers:
  github_tracker:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console] 